### PR TITLE
fix: enable complex resource ids in instantiate()

### LINKED ISSUE #154: How to return PathTemplate with complex resource identifiers?
I see you added support for complex resource identifiers with #125. However, I can't seem to figure out how to correctly return the instantiated template with populated variable values. For example, let's say I have a template `customers/{customer_id}/adGroupAds/{ad_group_id}~{ad_id}`. I can create the PathTemplate, which recognizes the `~` character as a separator. However, when I call the `instantiate(String... keysAndValues)` method like so `PATH_TEMPLATE.instantiate("customer_id", customerId, "ad_group_id", adGroupId, "ad_id", adId)`, the string returned does not have the `~` separator. The String that is returned is `customers/1234/adGroupAds/5678/1011` instead of the expected `customers/1234/adGroupAds/5678~1011`.

Is there a way to do this so that the resulting string still contains the complex resource identifier? Or did #125 not address this?

### PR DESCRIPTION
**Pull request by miraleung**
Fixes #154.

### CODE REVIEW

**Comment by devchas** [comment]
I just tested this out with a local build, and it seems to have fixed the problem. Thank you for the quick fix here! Any idea when this might make it into the next release. As mentioned in #154, we have another large body of work which depends on this feature, with a hard deadline in mid-July.

File: src/test/java/com/google/api/pathtemplate/PathTemplateTest.java [hunk 1]
```diff
@@ -377,6 +378,26 @@ public void complexResourceIdInParent() {
...
+
+    pattern = "projects/{foo}_{bar}/zones/*";
+    template = PathTemplate.create(pattern);
+    Map<String, String> match =
+        template.match("https://www.googleapis.com/compute/v1/projects/foo1_bar2/zones/azone");
+    Truth.assertThat(match).isNotNull();
+    Truth.assertThat(match.get("foo")).isEqualTo("foo1");
+    Truth.assertThat(match.get("bar")).isEqualTo("bar2");
+    variables = template.vars();
+    System.out.println("DEL: vars: " + variables);
```
Comment (elharo) [inline src/test/java/com/google/api/pathtemplate/PathTemplateTest.java:398]: This shouldn't be here

File: src/test/java/com/google/api/pathtemplate/PathTemplateTest.java [hunk 2]
```diff
@@ -377,6 +378,26 @@ public void complexResourceIdInParent() {
...
+  public void complexResourcePathTemplateVariables() {
+    String pattern =
+        "projects/{foo}_{bar}/zones/{zone_a}-{zone_b}_{zone_c}/machines/{cell1}.{cell2}";
+    PathTemplate template = PathTemplate.create(pattern);
+    Set<String> variables = template.vars();
+    Truth.assertThat(variables)
+        .containsExactly("foo", "bar", "zone_a", "zone_b", "zone_c", "cell1", "cell2");
+
+    pattern = "projects/{foo}_{bar}/zones/*";
+    template = PathTemplate.create(pattern);
```
Comment (elharo) [inline src/test/java/com/google/api/pathtemplate/PathTemplateTest.java:391]: local variables probably shouldn't be reused
