### PR TITLE
fix: Support delimiters(_-.~) as start or end characters for a segment.

### LINKED ISSUE #335: support `.` a beginning character in path template
Parsing of a template like `"/v1beta1/{parent=projects/*/locations/*/clusters/*}/.well-known/openid-configuration"` is currently failing with the following stack trace:

```
Exception in thread "main" com.google.api.pathtemplate.ValidationException: parse error: invalid begin or end character in '.well-known'
	at com.google.api.pathtemplate.PathTemplate.parseTemplate(PathTemplate.java:893)
	at com.google.api.pathtemplate.PathTemplate.create(PathTemplate.java:266)
	at com.google.api.pathtemplate.PathTemplate.create(PathTemplate.java:252)
	at com.google.api.generator.gapic.protoparser.HttpRuleParser.getPatternBindings(HttpRuleParser.java:186)
	at com.google.api.generator.gapic.protoparser.HttpRuleParser.parseHttpRuleHelper(HttpRuleParser.java:71)
	at com.google.api.generator.gapic.protoparser.HttpRuleParser.parse(HttpRuleParser.java:60)
	at com.google.api.generator.gapic.protoparser.Parser.parseMethods(Parser.java:695)
	at com.google.api.generator.gapic.protoparser.Parser.lambda$parseService$17(Parser.java:481)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.google.api.generator.gapic.protoparser.Parser.parseService(Parser.java:491)
	at com.google.api.generator.gapic.protoparser.Parser.parseServices(Parser.java:236)
	at com.google.api.generator.gapic.protoparser.Parser.parse(Parser.java:159)
	at com.google.api.generator.gapic.Generator.generateGapic(Generator.java:29)
	at com.google.api.generator.Main.main(Main.java:28)
--java_gapic_out: protoc-gen-java_gapic: Plugin failed with status code 1.
```

Gapic-generator (and `PathTemplate` class in particular) must support dot character (`.`) as a beginning of a token (like in `.well-known` element in the example above). 

[PathTemplate](https://github.com/googleapis/api-common-java/blob/main/src/main/java/com/google/api/pathtemplate/PathTemplate.java) class is located in api-common-java repository.

### PR DESCRIPTION
**Pull request by blakeli0**
Support delimiters(_-.~) as start or end characters for a segment if the segment does not contain complex resource names.

- A segment can start with a delimiter, as long as there is no `{` right after it.
- A segment can end with a delimiter, as long as there is no `}` right before it.
- A segment like `.{well}-{known}` or `{well}-{known}.` is invalid.
- A segment like `.well-known`, `.well-{known}` or `.-~{well-known}` is considered a literal hence is valid

Fixes #335  ☕️

BEGIN_COMMIT_OVERRIDE
fix: Support delimiters(_-.~) as start or end characters for a segment
END_COMMIT_OVERRIDE

### CODE REVIEW

File: src/main/java/com/google/api/pathtemplate/PathTemplate.java [hunk 1]
```diff
@@ -1015,6 +1013,20 @@ public String encode(String... values) {
     return builder.build();
   }
 
+  private static boolean isSegmentBeginOrEndInvalid(String seg) {
+    if (seg.length() == 1 && COMPLEX_DELIMITER_PATTERN.matcher(seg).find()) {
+      return true;
+    }
+    //A segment like .{well}-{known} or {well}-{known}. is invalid.
+    //A segment like .well-known or .well-{known} will be considered a literal hence is valid
+    return (COMPLEX_DELIMITER_PATTERN.matcher(seg.substring(0, 1)).find()
```
Comment (vam-google) [inline src/main/java/com/google/api/pathtemplate/PathTemplate.java:1022]: Minor: please consider reversing the order of conditions in `&&` to make sure that lighter ones are executed first (and potentially not needing to go to the much heavier regexp matching portion if the simpler ones are already false)

File: src/main/java/com/google/api/pathtemplate/PathTemplate.java [hunk 2]
```diff
@@ -1015,6 +1013,20 @@ public String encode(String... values) {
...
+            && seg.length() > 1
+            && seg.charAt(1) == '{')
+        || (COMPLEX_DELIMITER_PATTERN.matcher(seg.substring(seg.length() - 1)).find()
+            && seg.length() > 1
```
Comment (vam-google) [inline src/main/java/com/google/api/pathtemplate/PathTemplate.java:1026]: `seg.length() > 1` is redundantly mentioned in both portions of the OR statement.

File: src/test/java/com/google/api/pathtemplate/PathTemplateTest.java [hunk 3]
```diff
@@ -487,9 +487,6 @@ public void complexResourceBasicInvalidIds() {
   @Test
   public void complexResourceMultipleDelimiters() {
     thrown.expect(ValidationException.class);
-    PathTemplate.create("projects/*/zones/.-~{zone_a}");
```
Comment (vam-google) [inline src/test/java/com/google/api/pathtemplate/PathTemplateTest.java:490]: It feels this still should be an invalid input as this is the third type of case (not mentioined in PR description and in the comment in `isSegmentBeginOrEndInvalid` method). This a 2+ consecutive delimiter characters at the beginning of a segment. I understand that it is a super unlikely scenario, but please strongly consider taking this case into account as invalid, or clarify why this still shoudl be considered valid in the PR description and `isSegmentBeginOrEndInvalid` comment)

Comment (blakeli0) [reply src/test/java/com/google/api/pathtemplate/PathTemplateTest.java:490]: Even though super unlikely, but I would consider this a literal if it happens. 2+ consecutive delimiters are only a problem if they are in between `}` and '{', I can add more comments to clarify this scenario.

File: src/main/java/com/google/api/pathtemplate/PathTemplate.java (hunk 2 above)
Comment (blakeli0) [reply src/main/java/com/google/api/pathtemplate/PathTemplate.java:1026]: Yes, you are right, tested without `seg.length() > 1` and all test cases passed, will remove it.

File: src/main/java/com/google/api/pathtemplate/PathTemplate.java (hunk 1 above)
Comment (blakeli0) [reply src/main/java/com/google/api/pathtemplate/PathTemplate.java:1022]: The order cannot be changed since a segment may only contain one non-delimiter character, so we have to test the regex first.

File: src/main/java/com/google/api/pathtemplate/PathTemplate.java [hunk 4]
```diff
@@ -1015,6 +1013,20 @@ public String encode(String... values) {
...
+  private static boolean isSegmentBeginOrEndInvalid(String seg) {
+    // A segment is invalid if it contains only one character and the character is a delimiter
+    if (seg.length() == 1 && COMPLEX_DELIMITER_PATTERN.matcher(seg).find()) {
+      return true;
+    }
+    // A segment can start with a delimiter, as long as there is no { right after it.
+    // A segment can end with a delimiter, as long as there is no } right before it.
+    // e.g. Invalid: .{well}-{known}, {well}-{known}-
+    // Valid: .well-known, .well-{known}, .-~{well-known}, these segments are all considered as literals for matching
+    return (COMPLEX_DELIMITER_PATTERN.matcher(seg.substring(0, 1)).find() && seg.charAt(1) == '{')
```
Comment (chanseokoh) [inline src/main/java/com/google/api/pathtemplate/PathTemplate.java:1025]: Just to confirm: what if the segment is two consecutive delimiters (e.g.,, `..` of length 2)? According to this check, it's valid. Perhaps this is checked in other places?

Also, `well.{known}.stuff` is valid, right?

Comment (blakeli0) [reply src/main/java/com/google/api/pathtemplate/PathTemplate.java:1025]: yes, 2+ consecutive delimiters in between curly brackets are checked [here](https://github.com/googleapis/api-common-java/blob/6a8a0a44fbf942ea6224ab3d8d4b3bcc6c79c5b4/src/main/java/com/google/api/pathtemplate/PathTemplate.java#L896), it's valid if they are in the beginning since they are considered literals.  
`well.{known}.stuff` is also considered a literal hence is valid.

File: src/main/java/com/google/api/pathtemplate/PathTemplate.java (hunk 1 above)
Comment (vam-google) [reply src/main/java/com/google/api/pathtemplate/PathTemplate.java]: I'm a big confused. In the original code, each `&&` segment also had `seg.length() > 1` which was guaranteeing that seg is at lest 2 characters long, so both `seg.charAt(1) == '{'` and `seg.charAt(seg.length() - 2) == '}'` would not fail. Instead of removing `seg.length() > 1` from both segments, we could just put it infront of the whole return block condition, and that wuold allow testing for `seg.charAt(1) == '{'` and `seg.charAt(seg.length() - 2) == '}'` prior the regexp parts without risk getting out of bounds exception which is preferable, since  these are more lightweight operations and if they are false we would not even get into regexp part. 

But all that is micro-optimization stuff, so I'm fine with how it is now.
On a side note, the current code would fail if seg is an empty string, but I'm not sure if it is even possible.

**Review by vam-google — APPROVED** [review]
LGTM, but please check the `seg.length() > 1` check comment first

File: src/main/java/com/google/api/pathtemplate/PathTemplate.java (hunk 1 above)
Comment (blakeli0) [reply src/main/java/com/google/api/pathtemplate/PathTemplate.java]: Yes it would fail on empty String but that's not possible because of the trimming [here](https://github.com/googleapis/api-common-java/blob/6a8a0a44fbf942ea6224ab3d8d4b3bcc6c79c5b4/src/main/java/com/google/api/pathtemplate/PathTemplate.java#L881)

**Comment by blakeli0** [comment]
> LGTM, but please check the `seg.length() > 1` check comment first
Thanks, I see what you mean now, sorry I misunderstood you earlier. On the other hand, I think the way it is now might be better since it cleaner and easier to read. Moving `seg.length() > 1` would only benefit if the segment containsone character which I think is a very rare case.

**Review by meltsufin — APPROVED** [review]
